data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.coco_dataset
        class: CoCoDataset
        CoCoDataset:
          model_name: '''D0'''
          image_dir: '''dataset/birdview_vehicles/val'''
          label_path: '''dataset/birdview_vehicles/annotations/instances_val.json'''
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
      batch_size: 16
      shuffle: False
      drop_last: False
      pin_memory: True
      num_workers: 12
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.efficient_det
  class: Model
  Model:
    num_classes: 2
    model_name: '''D0'''
    scales: ['2 ** 0', '2 ** (1.0 / 3.0)', '2 ** (2.0 / 3.0)']
    aspect_ratios: [0.5, 1., 2.]
    iou_threshold: 0.45
    score_threshold: 0.2

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      coco_eval:
        module: flame.core.metric.COCO_eval
        class: COCOEvaluator
        COCOEvaluator:
          model_name: '''D0'''
          detection_path: '''checkpoint/birdview_vehicles/efficientdet-d0/2205191442/birdview_det_val.json'''
          ground_truth_path: '''checkpoint/birdview_vehicles/efficientdet-d0/2205191442/birdview_gt_val.json'''
          classes:
            large-vehicle: 0
            small-vehicle: 1
          output_transform: 'lambda x: (x[0], x[1], x[2])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/birdview_vehicles/efficientdet-d0/2205191442/best_model_42_focal_loss=-1.3001.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/birdview_vehicles/efficientdet-d0/2205191442/best_model_42_focal_loss=-1.3001/val'''
    model_name: '''D0'''
    classes:
      large-vehicle: [[255, 0, 0], 0]  # color, class_idx, area_threshold
      small-vehicle: [[0, 255, 0], 1]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.evaluator
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
