data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          compound_coef: 0
          dirnames:
            - '''dataset/TABLE/test/ICDAR2013'''
            - '''dataset/TABLE/test/PubLayNet'''
          image_patterns: ['''*.jpg''', '''*.png''', '''*.jpeg''', '''*.JPG''', '''*.PNG''', '''*.JPEG''']
          label_patterns: ['''*.json''']
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            # TABLE: 0
            borderless_table: 0
            bordered_table: 0
            color_table: 0
      batch_size: 8
      shuffle: False
      num_workers: 12
      pin_memory: True
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.efficientdet
  class: EfficientDet
  EfficientDet:
    head_only: False
    num_classes: 1
    compound_coef: 0
    backbone_pretrained: False
    scales: ['2 ** 0', '2 ** (1.0 / 3.0)', '2 ** (2.0 / 3.0)']
    aspect_ratios: ['(1.0, 1.0)', '(1.4, 0.7)', '(0.7, 1.4)', '(1.8, 0.3)']
    iou_threshold: 0.2
    score_threshold: 0.2

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      mAP:
        module: flame.handlers.metrics.mean_average_precision.eval
        class: Evaluator
        Evaluator:
          eval_fn:
            module: flame.handlers.metrics.mean_average_precision.mean_average_precision
            class: MeanAveragePrecision
            MeanAveragePrecision:
              classes:
                TABLE: 0
              iou_threshold: 0.5
              method: '''every_point_interpolation'''
          output_transform: 'lambda x: (x[0], x[1])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/TABLE/efficientdet-d0/2108161629/best_model_67_mAP=0.9785.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/TABLE/efficientdet-d0/2108161629/best_model_67_mAP=0.9785/test/'''
    compound_coef: 0
    classes:
      TABLE: [[0, 0, 255], 0]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.tester
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
