module: detector
class: Detector
Detector:
  model:
    module: flame.core.model.efficient_det.efficientdet
    class: EfficientDet
    EfficientDet:
      num_classes: 80
      compound_coef: 0
      scales: ['2 ** 0', '2 ** (1.0 / 3.0)', '2 ** (2.0 / 3.0)']
      aspect_ratios: ['(1.0, 1.0)', '(1.4, 0.7)', '(0.7, 1.4)']
      iou_threshold: 0.2
      score_threshold: 0.2
  weight_path: '''../checkpoint/checkpoint/COCO/2109052137/best_model_96_focal_loss=-1.6836.pt'''
  batch_size: 1
  compound_coef: 0
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  device: '''cpu'''

  # COCO (80 classes)
  classes:
    0: '''__background__'''
    1: '''person'''
    2: '''bicycle'''
    3: '''car'''
    4: '''motorcycle'''
    5: '''airplane'''
    6: '''bus'''
    7: '''train'''
    8: '''truck'''
    9: '''boat'''
    10: '''traffic light'''
    11: '''fire hydrant'''
    12: '''stop sign'''
    13: '''parking meter'''
    14: '''bench'''
    15: '''bird'''
    16: '''cat'''
    17: '''dog'''
    18: '''horse'''
    19: '''sheep'''
    20: '''cow'''
    21: '''elephant'''
    22: '''bear'''
    23: '''zebra'''
    24: '''giraffe'''
    25: '''backpack'''
    26: '''umbrella'''
    27: '''handbag'''
    28: '''tie'''
    29: '''suitcase'''
    30: '''frisbee'''
    31: '''skis'''
    32: '''snowboard'''
    33: '''sports ball'''
    34: '''kite'''
    35: '''baseball bat'''
    36: '''baseball glove'''
    37: '''skateboard'''
    38: '''surfboard'''
    39: '''tennis racket'''
    40: '''bottle'''
    41: '''wine glass'''
    42: '''cup'''
    43: '''fork'''
    44: '''knife'''
    45: '''spoon'''
    46: '''bowl'''
    47: '''banana'''
    48: '''apple'''
    49: '''sandwich'''
    50: '''orange'''
    51: '''broccoli'''
    52: '''carrot'''
    53: '''hot dog'''
    54: '''pizza'''
    55: '''donut'''
    56: '''cake'''
    57: '''chair'''
    58: '''couch'''
    59: '''potted plant'''
    60: '''bed'''
    61: '''dining table'''
    62: '''toilet'''
    63: '''tv'''
    64: '''laptop'''
    65: '''mouse'''
    66: '''remote'''
    67: '''keyboard'''
    68: '''cell phone'''
    69: '''microwave'''
    70: '''oven'''
    71: '''toaster'''
    72: '''sink'''
    73: '''refrigerator'''
    74: '''book'''
    75: '''clock'''
    76: '''vase'''
    77: '''scissors'''
    78: '''teddy bear'''
    79: '''hair drier'''
    80: '''toothbrush'''

  # # PASCAL VOC (20 classes)
  # classes:
  #   0: '''aeroplane'''
  #   1: '''bicycle'''
  #   2: '''bird'''
  #   3: '''boat'''
  #   4: '''bottle'''
  #   5: '''bus'''
  #   6: '''car'''
  #   7: '''cat'''
  #   8: '''chair'''
  #   9: '''cow'''
  #   10: '''diningtable'''
  #   11: '''dog'''
  #   12: '''horse'''
  #   13: '''motorbike'''
  #   14: '''person'''
  #   15: '''pottedplant'''
  #   16: '''sheep'''
  #   17: '''sofa'''
  #   18: '''train'''
  #   19: '''tvmonitor'''
