module: detector
class: Detector
Detector:
  model:
    module: flame.core.model.efficient_det.efficientdet
    class: EfficientDet
    EfficientDet:
      num_classes: 1
      model_name: '''D0'''
      scales: ['2 ** 0', '2 ** (1.0 / 3.0)', '2 ** (2.0 / 3.0)']
      aspect_ratios: [0.25, 0.5, 1., 2., 4.]  # anchor_width / anchor_height
      iou_threshold: 0.2
      score_threshold: 0.5
  classes:
    0: '''EPASS'''
  model_name: '''D0'''
  weight_path: '''models/EPASS/2204011232/best_model_166_focal_loss=-0.4426.pt'''
  batch_size: 1
  mean: '(0.485, 0.456, 0.406)'
  std: '(0.229, 0.224, 0.225)'
  device: '''cpu'''
