module: detector
class: Detector
Detector:
  model:
    module: flame.core.model.efficient_det.efficientdet
    class: EfficientDet
    EfficientDet:
      num_classes: 20
      model_name: '''D0'''
      scales: ['2 ** 0', '2 ** (1.0 / 3.0)', '2 ** (2.0 / 3.0)']
      aspect_ratios: [1., 2., 0.5]  # anchor_width / anchor_height
      iou_threshold: 0.2
      score_threshold: 0.5
  model_name: '''D0'''
  weight_path: '''models/PASCAL/efficientdet-d0/2110221358/best_model_21_focal_loss=-1.2464.pt'''
  batch_size: 1
  mean: '(0.485, 0.456, 0.406)'
  std: '(0.229, 0.224, 0.225)'
  device: '''cpu'''
  classes:  # PASCAL VOC (20 classes)
    0: '''aeroplane'''
    1: '''bicycle'''
    2: '''bird'''
    3: '''boat'''
    4: '''bottle'''
    5: '''bus'''
    6: '''car'''
    7: '''cat'''
    8: '''chair'''
    9: '''cow'''
    10: '''diningtable'''
    11: '''dog'''
    12: '''horse'''
    13: '''motorbike'''
    14: '''person'''
    15: '''pottedplant'''
    16: '''sheep'''
    17: '''sofa'''
    18: '''train'''
    19: '''tvmonitor'''
