data:
  test:
    module: torch.utils.data
    class: DataLoader
    DataLoader:
      dataset:
        module: flame.core.data.labelme_dataset
        class: LabelmeDataset
        LabelmeDataset:
          model_name: '''D0'''
          dirnames:
            - '''dataset/EPASS/test/'''
          image_patterns: ['''*.*g''', '''*.*G''']
          label_patterns: ['''*.json''']
          mean: [0.485, 0.456, 0.406]
          std: [0.229, 0.224, 0.225]
          classes:
            EPASS_TYPE_1: 0
            EPASS_TYPE_2: 0
            EPASS_TYPE_3: 0
            EPASS_TYPE_4: 0
            EPASS_TYPE_5: 0
      batch_size: 16
      shuffle: False
      num_workers: 12
      pin_memory: True
      drop_last: False
      collate_fn: 'lambda batch:tuple(zip(*batch))'

model:
  module: flame.core.model.efficient_det
  class: Model
  Model:
    num_classes: 1
    model_name: '''D0'''
    backbone_pretrained: False
    scales: [1., '2 ** (1 / 3)', '2 ** (2 / 3)']
    aspect_ratios: [0.25, 0.5, 1., 2., 4.]  # anchor_width / anchor_height
    iou_threshold: 0.2
    score_threshold: 0.5

metrics:
  module: flame.handlers.metrics.metrics
  class: Metrics
  Metrics:
    metrics:
      coco_eval:
        module: flame.core.metric.COCO_eval
        class: COCOEvaluator
        COCOEvaluator:
          model_name: '''D0'''
          detection_path: '''checkpoint/EPASS/efficientdet-d0/EXP2/2204061354/epass_det_val.json'''
          ground_truth_path: '''checkpoint/EPASS/efficientdet-d0/EXP2/2204061354/epass_gt_val.json'''
          classes:
            EPASS: 0
          output_transform: 'lambda x: (x[0], x[1], x[2])'
    attach_to:
      engine: '''test'''

screenlogger:
  module: flame.handlers.screenlogger
  class: ScreenLogger
  ScreenLogger:
    eval_names:
      - '''test'''

checkpoint_loader:
  module: flame.handlers.checkpoint
  class: CheckpointLoader
  CheckpointLoader:
    checkpoint_path: '''checkpoint/EPASS/efficientdet-d0/EXP2/2204061354/best_model_107_focal_loss=-0.3236.pt'''
    mode: '''test'''

predictor:
  module: flame.handlers.region_predictor
  class: RegionPredictor
  RegionPredictor:
    evaluator_name: '''engine'''
    output_dir: '''checkpoint/EPASS/efficientdet-d0/EXP2/2204061354/best_model_107_focal_loss=-0.3236/test/'''
    model_name: '''D0'''
    classes:
      EPASS: [[0, 0, 255], 0]
    output_transform: 'lambda x: (x[0], x[-1])'

engine:
  module: flame.core.engine.evaluator
  class: Evaluator
  Evaluator:
    dataset: config['data']['test']
    device: '''cuda'''

extralibs:
  torch: torch
